### ISSUE TITLE
Produire les rapports de tests Junit

### ISSUE THREAD

**Issue by urosselet** [HE-Arc-Indus/sp18-recap-ci-seaftyfirst#1]
Il faudrait modifier votre Jenkinsfile pour produire les rapports de tests Junit dans tous les cas.

**Comment by aemeri** [comment]
Jenkinsfile amélioré et test OK depuis Jenkins avec création d'un rapport.

**Comment by odilee** [comment]
Résultat des tests disponibles. 


Tests run: 5, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.199 s
[INFO] Finished at: 2018-05-15T03:00:59+00:00
[INFO] Final Memory: 8M/88M
[INFO] ------------------------------------------------------------------------
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Declarative: Post Actions)
[Pipeline] junit
Recording test results
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: SUCCESS
